FROM node:16-alpine

WORKDIR /usr/src/app

COPY . .
RUN npm install
EXPOSE 3000
CMD ["npm", "run", "dev"]

# docker run --name svelte_template -it -p 3000:3000 -v "$(pwd)/src:/usr/src/app/src" --rm $(docker build -q -f Dockerfile.dev .)
