FROM node:16-alpine

WORKDIR /usr/src/app

COPY rollup.config.js ./
COPY package*.json ./

RUN npm install

COPY ./src ./src
COPY ./public ./public

RUN npm run-script build

EXPOSE 5000

ENV HOST=0.0.0.0

CMD ["npm", "run", "dev"]
# DEV:
# docker build -t svelte/todo -f dev.Dockerfile .
# docker run -it -p 5000:5000 -v "$(pwd)/src:/usr/src/app/src" --name svelte_todo svelte/todo
