FROM node:16-alpine AS build

WORKDIR /app
COPY . ./
RUN npm install
EXPOSE 3000
RUN npm run build

# RUN npm run build

# docker run --name svelte_template -it -p 80:80 --rm $(docker build -q -f Dockerfile.build .)


FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
